config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  default_scope { order(created_at: :desc) }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found
  
  protected
  
  def resource_not_found
    
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render :new
    end
  end

  def show
  end

  def edit
    unless @article.user == current_user
      flash[:alert] = "You can only edit your own article."
      redirect_to root_path
    end
  end

  def update
    unless @article.user == current_user
      flash[:alert] = "You can only edit your own article."
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:success] = "Article has been updated"
        redirect_to @article
      else
        flash.now[:danger] = "Article has not been updated"
        render :edit
      end
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    end
  end

  protected

  def resource_not_found
    message = "The article you are looking for could not be found"
    flash[:alert] = message
    redirect_to root_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @article.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@article.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% @article.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-11">
          <%= f.text_field :title, class: 'form-control', placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :body %>
        </div>
        <div class="col-md-11">
          <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: "Body of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h3 class="text-center">Editing an Article</h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
<%= link_to "New Article", new_article_path, class: "btn btn-default btn-lg", id: "new-article-btn" %>
<% end %>
<% if @articles.empty? %>
  <h1 id="no-articles">No  Articles Created</h1>
<% else %>
  <% @articles.each do |article| %>
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class="article-body">
        <%= truncate(article.body, length: 500, omission: '...') %>
      </div>
      <div class="author">
        <small>Created by: <%= article.user.email %></small>
      </div>
    </div>
  <% end %>
<% end %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding New Article</h3>
<%= render 'form' %>

app/views/articles/show.html.erb
<article class="article-detail">
  <h1 class="article-detail-title"><%= @article.title %></h1>

  <div class="glyphicon glyphicon-calendar" id="article-date"><%= @article.created_at.strftime("%b %d %Y")%></div>

  <div class="article-body">
    <%= @article.body %>
  </div>
  <% if user_signed_in? and current_user == @article.user %>
  <div class="edit-delete">
    <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary btn-lg btn-space" %>
    <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are you sure want to delete article?"}, class: "btn btn-primary btn-lg btn-space" %>
  </div>
  <% end %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/main' %>
  </body>
</html>

app/views/shared/_header.html.erb
 <header role="banner">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blog App", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">

          <li class="active"><%= link_to "Authors", "#" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
          <% if user_signed_in? %>
            <p class="navbar-text">Signed in as <%="#{current_user.email}" %></p>
          <% end %>
        </ul>
      </div>
    </nav>
</header>

app/views/shared/_main.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key.in?(['success','notice', 'alert']) ? 'success' : 'danger' %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>